export const apiBase = 'http://localhost:5000/api';

export const authConstants = {
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',

  AUTH_SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',
  AUTH_SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',

  COOKIE_KEY: 'auth_user'
};

export const articleConstants = {
  ARTICLE_GETLIST_FAILURE: 'ARTICLE_GETLIST_FAILURE',
  ARTICLE_GETLIST_REQUEST: 'ARTICLE_GETLIST_REQUEST',
  ARTICLE_GETLIST_SUCCESS: 'ARTICLE_GETLIST_SUCCESS',

  ARTICLE_GET_REQUEST: 'ARTICLE_GET_REQUEST',
  ARTICLE_GET_SUCCESS: 'ARTICLE_GET_SUCCESS',
  ARTICLE_GET_FAILURE: 'ARTICLE_GET_FAILURE'
};

export const headerConstats = {
  HEADER_SET_ACTIVE_ITEM_REQUEST: 'HEADER_SET_ACTIVE_ITEM_REQUEST',
  HEADER_SET_ACTIVE_ITEM_SUCCESS: 'HEADER_SET_ACTIVE_ITEM_SUCCESS',
  HEADER_SET_ACTIVE_ITEM_FAILURE: 'HEADER_SET_ACTIVE_ITEM_FAILURE'
};
