export const authConstants = {
  AUTH_SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
  AUTH_SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',

  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE'
};
