export const apiBase = 'http://localhost:5000/api';

export const authConstants = {
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',

  AUTH_SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',
  AUTH_SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
  AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',

  COOKIE_KEY: 'auth_user'
};

export const articleConstants = {
  ARTICLE_GETLIST_FAILURE: 'ARTICLE_GETLIST_FAILURE',
  ARTICLE_GETLIST_REQUEST: 'ARTICLE_GETLIST_REQUEST',
  ARTICLE_GETLIST_SUCCESS: 'ARTICLE_GETLIST_SUCCESS'
};
